"""Provider-specific message preprocessing applied before cache lookup."""

import copy
import json
from typing import Any, Callable, Dict, List, Optional, Tuple

from .response_format import (
    apply_response_format_transport,
    ensure_response_format_spec,
    get_response_format_spec,
)
from ..types import PromptCacheParam

CONCURRENT_USER_MESSAGES_EXPLANATION = (
    "For all user messages which are represented in JSON format, please treat each "
    "item in the list as a separate message. The user message is shown in JSON format "
    "because this API does not natively support concurrent user messages (which is "
    "what actually occurred), and concurrent user messages are being represented this "
    "way instead."
)

THINKING_PREFILL_EXPLANATION = (
    "The conversation history up to this point is expressed below in JSON format "
    "due to schema constraints:\n"
)

THINKING_COMPLIANCE_CONTEXT_HEADER = "[Prior tool execution context]"
THINKING_COMPLIANCE_CONTEXT_FOOTER = "[Continue from here]"
COMPLETED_TOOL_CONTEXT_HEADER = (
    "[Prior tool execution context]\n"
    "The entries below are authoritative records of tool calls that were already "
    "started in prior turns. Do not repeat a tool call solely to obtain a result "
    "that is already present here. Treat completed results as final, treat "
    "pending entries as already in flight, and continue from this state."
)
COMPLETED_TOOL_CONTEXT_FOOTER = (
    "[Continue from the tool execution state above. If the requested work is "
    "complete, answer the user instead of re-calling completed tools.]"
)
COMPLETED_TOOL_IMAGE_CONTEXT_FOOTER = (
    "The image(s) above are already part of completed tool results. Do not call "
    "the same image-producing tool again. Answer using the completed image "
    "result and text context above."
)

TOOL_CHOICE_REQUIRED_INSTRUCTION = (
    "IMPORTANT: You MUST call a tool on this turn. A tool call is required - "
    "do not respond with text only. Select the most appropriate tool and call it."
)

SOFT_FORCED_TOOL_CHOICE_PROVIDERS = {"deepseek", "minimax", "xiaomi-mimo"}


def _move_system_messages_to_front(
    messages: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Move all system messages to the beginning, preserving relative order."""
    system = [m for m in messages if m.get("role") == "system"]
    non_system = [m for m in messages if m.get("role") != "system"]
    return system + non_system


# ═══════════════════════════════════════════════════════════════════════════════
# Thinking Compliance: Transform non-compliant tool call messages
# ═══════════════════════════════════════════════════════════════════════════════
#
# When Claude extended thinking is enabled (reasoning_effort is set), Anthropic
# requires that all assistant messages have thinking_blocks. However, synthetic
# messages (generated by tool loops for bookkeeping) or messages from before
# thinking was enabled won't have these blocks.
#
# This transformation detects such non-compliant messages and converts them to
# user context messages, preserving the information while making the transcript
# API-compliant.


def _is_non_compliant_assistant_tool_call(msg: Dict[str, Any]) -> bool:
    """
    Check if an assistant message with tool_calls lacks thinking_blocks.

    When thinking mode is enabled, Claude requires thinking_blocks on all
    assistant messages. An assistant message with tool_calls but no
    thinking_blocks is non-compliant and needs transformation.

    Args:
        msg: A message dict to check.

    Returns:
        True if the message is an assistant message with tool_calls but no
        thinking_blocks, False otherwise.
    """
    if not isinstance(msg, dict):
        return False
    if msg.get("role") != "assistant":
        return False
    if not msg.get("tool_calls"):
        return False
    # Has tool_calls but no thinking_blocks → non-compliant
    return not msg.get("thinking_blocks")


def _has_non_compliant_tool_calls(messages: List[Dict[str, Any]]) -> bool:
    """
    Check if any assistant message with tool_calls lacks thinking_blocks.

    Args:
        messages: List of message dicts.

    Returns:
        True if any assistant message with tool_calls is missing thinking_blocks.
    """
    return any(_is_non_compliant_assistant_tool_call(m) for m in messages)


def _transform_tool_calls_to_context(
    messages: List[Dict[str, Any]],
    *,
    context_header: str = THINKING_COMPLIANCE_CONTEXT_HEADER,
    context_footer: str = THINKING_COMPLIANCE_CONTEXT_FOOTER,
    image_context_footer: Optional[str] = None,
    predicate: Optional[Callable[[Dict[str, Any]], bool]] = None,
) -> List[Dict[str, Any]]:
    """
    Transform non-compliant assistant tool call messages into user context.

    When Claude extended thinking is enabled but an assistant message has
    tool_calls without thinking_blocks, this function transforms that message
    (and its paired tool results) into a user message with JSON context.

    The transformation:
    1. Finds assistant messages matching the predicate (or all non-compliant ones)
    2. Collects the assistant message and all following tool result messages
    3. Replaces them with a single user message containing the JSON representation

    Args:
        messages: List of message dicts to transform.
        context_header: Header text for the context block.
        context_footer: Footer text prompting continuation.
        predicate: Optional function to determine which assistant messages to
                   transform. If None, transforms all non-compliant messages.

    Returns:
        New list with non-compliant messages transformed to user context.
    """
    if predicate is None:
        predicate = _is_non_compliant_assistant_tool_call

    result = []
    i = 0

    while i < len(messages):
        msg = messages[i]

        # Check if this is an assistant message we should transform
        if predicate(msg):
            # Collect this assistant message and all following tool messages
            context_messages = [msg]
            j = i + 1

            # Collect all tool result messages that follow
            while j < len(messages) and messages[j].get("role") == "tool":
                context_messages.append(messages[j])
                j += 1

            # Extract images from collected messages before JSON serialization.
            # Each image is replaced with an [image] placeholder so the JSON
            # still shows where images appeared in the tool results.
            all_images: List[Dict[str, Any]] = []
            cleaned: List[Dict[str, Any]] = []
            for cm in context_messages:
                non_image, images = _extract_image_blocks(
                    cm.get("content", ""),
                    placeholder=True,
                )
                if images:
                    all_images.extend(images)
                    cleaned.append({**cm, "content": non_image})
                else:
                    cleaned.append(cm)

            context_json = json.dumps(cleaned, indent=2)
            context_text = f"{context_header}\n{context_json}\n{context_footer}"

            if all_images:
                content: Any = [
                    {"type": "text", "text": context_text},
                    *all_images,
                ]
                if image_context_footer is not None:
                    content.append({"type": "text", "text": image_context_footer})
                result.append({"role": "user", "content": content})
            else:
                result.append({"role": "user", "content": context_text})

            i = j  # Skip past all collected messages
        else:
            result.append(msg)
            i += 1

    return result


def _apply_thinking_compliance(
    messages: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Ensure all assistant messages with tool_calls have thinking_blocks.

    For Claude extended thinking mode, assistant messages must have
    thinking_blocks. This function transforms any non-compliant messages
    (those with tool_calls but no thinking_blocks) into user context messages.

    Args:
        messages: List of message dicts.

    Returns:
        New list with non-compliant messages transformed.
    """
    if not _has_non_compliant_tool_calls(messages):
        return messages

    return _transform_tool_calls_to_context(messages)


def _transform_completed_tool_calls_to_context(
    messages: List[Dict[str, Any]],
    *,
    context_header: str = THINKING_COMPLIANCE_CONTEXT_HEADER,
    context_footer: str = THINKING_COMPLIANCE_CONTEXT_FOOTER,
    image_context_footer: Optional[str] = None,
) -> List[Dict[str, Any]]:
    completed_call_message_ids = {
        id(msg)
        for idx, msg in enumerate(messages[:-1])
        if msg.get("role") == "assistant"
        and msg.get("tool_calls")
        and messages[idx + 1].get("role") == "tool"
    }
    if not completed_call_message_ids:
        return messages

    return _transform_tool_calls_to_context(
        messages,
        context_header=context_header,
        context_footer=context_footer,
        image_context_footer=image_context_footer,
        predicate=lambda msg: id(msg) in completed_call_message_ids,
    )


def _strip_thinking_blocks(
    messages: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Remove thinking_blocks from all messages.

    When reasoning/thinking is disabled but messages from a previous
    thinking-enabled conversation contain thinking_blocks, Anthropic rejects with:
    "When thinking is disabled, an assistant message cannot contain thinking."

    This function removes thinking_blocks from all messages to make them
    compatible with non-thinking requests.

    Args:
        messages: List of message dicts.

    Returns:
        New list with thinking_blocks removed from all messages.
    """
    result = []
    for msg in messages:
        if msg.get("thinking_blocks"):
            # Create a copy without thinking_blocks
            new_msg = {k: v for k, v in msg.items() if k != "thinking_blocks"}
            result.append(new_msg)
        else:
            result.append(msg)
    return result


def _find_first_real_assistant_index(messages: List[Dict[str, Any]]) -> Optional[int]:
    """
    Find the index of the first assistant message with thinking_blocks (real response).
    Returns None if no real assistant responses exist.
    """
    for i, msg in enumerate(messages):
        if msg.get("role") == "assistant" and msg.get("thinking_blocks"):
            return i
    return None


def _has_prefilled_assistant_before_real(messages: List[Dict[str, Any]]) -> bool:
    """
    Check if there are prefilled assistant messages (without thinking_blocks)
    that appear before any real assistant response (with thinking_blocks).
    """
    first_real_idx = _find_first_real_assistant_index(messages)

    # Check messages up to (but not including) first real response
    check_until = first_real_idx if first_real_idx is not None else len(messages)

    for i in range(check_until):
        msg = messages[i]
        if msg.get("role") == "assistant" and not msg.get("thinking_blocks"):
            return True
    return False


def _convert_prefill_to_system_message(
    messages: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Convert prefilled messages to a system message for Anthropic thinking mode.

    When thinking mode is enabled, Anthropic requires assistant messages to have
    thinking_blocks. For prefilled/synthetic assistant messages, we convert them
    to a JSON representation in the system message.

    Only messages BEFORE the first real assistant response (one with thinking_blocks)
    are converted. Messages from the first real response onwards are kept intact.

    Image blocks are extracted before JSON serialization and replaced with
    ``[image]`` placeholders in the JSON. The native image blocks are placed
    in a follow-up user message so the LLM receives them as image tokens
    rather than text-serialized base64. Images cannot go in the system
    message because Anthropic's ``system`` parameter only accepts text
    blocks — placing image blocks there causes a 400 error on code paths
    that don't use tool calling (e.g., ProactiveSpeech with
    ``response_format``).
    """
    first_real_idx = _find_first_real_assistant_index(messages)

    # Determine which messages to convert vs keep
    if first_real_idx is not None:
        to_convert = messages[:first_real_idx]
        to_keep = messages[first_real_idx:]
    else:
        to_convert = messages
        to_keep = []

    # Extract existing system message content from the portion to convert.
    # System messages may have list content (text + image blocks) when
    # Some prompt builders embed screenshots.  Extract text as string
    # and collect any images so they can be routed to a user message.
    system_content = ""
    system_images: List[Dict[str, Any]] = []
    non_system_to_convert = []
    for msg in to_convert:
        if msg.get("role") == "system":
            content = msg.get("content", "")
            if isinstance(content, list):
                text_parts = []
                for block in content:
                    if isinstance(block, dict):
                        if block.get("type") == "image_url":
                            system_images.append(block)
                        elif block.get("type") == "text":
                            text_parts.append(block.get("text", ""))
                    elif isinstance(block, str):
                        text_parts.append(block)
                content = "\n".join(text_parts)
            if system_content:
                system_content += "\n\n"
            system_content += content
        else:
            non_system_to_convert.append(msg)

    # Build result
    result = []

    # Extract image blocks before JSON serialization. Each extracted image
    # is replaced with an [image] placeholder in the message content so the
    # JSON still shows where images appeared.
    all_extracted_images: List[Dict[str, Any]] = list(system_images)
    cleaned_messages: List[Dict[str, Any]] = []
    for msg in non_system_to_convert:
        non_image_content, image_blocks = _extract_image_blocks(
            msg.get("content", ""),
            placeholder=True,
        )
        if image_blocks:
            all_extracted_images.extend(image_blocks)
            cleaned_messages.append({**msg, "content": non_image_content})
        else:
            cleaned_messages.append(msg)

    # Add system message with converted content (if any non-system messages to convert)
    if cleaned_messages:
        if system_content:
            system_content += "\n\n"
        system_content += THINKING_PREFILL_EXPLANATION
        system_content += json.dumps(cleaned_messages, indent=4)

    if system_content:
        result.append({"role": "system", "content": system_content})

    # Add continuation prompt if we converted everything (no real messages to keep)
    if not to_keep:
        if all_extracted_images:
            user_content: Any = [
                {"type": "text", "text": "[continue]"},
                *all_extracted_images,
            ]
            result.append({"role": "user", "content": user_content})
        else:
            result.append({"role": "user", "content": "[continue]"})
    else:
        if all_extracted_images:
            user_content = [
                {"type": "text", "text": "[Visual context from prior conversation]"},
                *all_extracted_images,
            ]
            result.append({"role": "user", "content": user_content})
        result.extend(to_keep)

    return result


_IMAGE_PLACEHOLDER_BLOCK = {"type": "text", "text": "[image]"}


def _extract_image_blocks(
    content: Any,
    *,
    placeholder: bool = False,
) -> Tuple[Any, List[Dict[str, Any]]]:
    """
    Extract image blocks from content, returning (non-image content, image blocks).

    If content is a list, separates image blocks from other blocks.
    If content is a string or other type, returns it unchanged with empty image list.

    When *placeholder* is True, each extracted image is replaced in-situ with
    an ``[image]`` text block so the surrounding context still shows that an
    image existed at that position.
    """
    if not isinstance(content, list):
        return content, []

    image_blocks = []
    other_blocks = []

    for block in content:
        if isinstance(block, dict) and block.get("type") == "image_url":
            image_blocks.append(block)
            if placeholder:
                other_blocks.append(dict(_IMAGE_PLACEHOLDER_BLOCK))
        else:
            other_blocks.append(block)

    # If all blocks were images and no placeholders, return empty list
    if not other_blocks:
        return [], image_blocks
    return other_blocks, image_blocks


def _combine_adjacent_user_messages(
    messages: List[Dict[str, Any]],
) -> Tuple[List[Dict[str, Any]], bool]:
    """
    Combine adjacent user messages into JSON content array format.
    Returns (result, whether_any_combining_occurred).

    Image blocks are preserved as native blocks in the combined message,
    not JSON-serialized, to maintain their semantic meaning.
    """
    if not messages:
        return [], False

    result = []
    combined_any = False
    i = 0

    while i < len(messages):
        msg = messages[i]

        if msg.get("role") != "user":
            result.append(msg)
            i += 1
            continue

        # Collect adjacent user messages
        user_contents = []
        all_image_blocks = []
        while i < len(messages) and messages[i].get("role") == "user":
            content = messages[i].get("content", "")
            non_image_content, image_blocks = _extract_image_blocks(content)
            user_contents.append(non_image_content)
            all_image_blocks.extend(image_blocks)
            i += 1

        if len(user_contents) == 1:
            result.append(msg)
        else:
            combined_any = True
            # Build list of user messages for JSON dump (excluding images)
            # Each message preserves its original content structure
            user_messages = []
            for c in user_contents:
                if isinstance(c, str):
                    # Simple string content
                    user_messages.append({"role": "user", "content": c})
                elif isinstance(c, list) and c:
                    # List content with non-image blocks
                    user_messages.append({"role": "user", "content": c})
                # Skip empty lists (all content was images)

            # Create the combined content: JSON-dumped messages + native image blocks
            json_content = json.dumps(user_messages, indent=4)

            if all_image_blocks:
                # Mixed content: JSON text block + native image blocks
                combined_content = [
                    {"type": "text", "text": json_content},
                    *all_image_blocks,
                ]
                result.append({"role": "user", "content": combined_content})
            else:
                # No images, just JSON string as before
                result.append({"role": "user", "content": json_content})

    return result, combined_any


CACHE_CONTROL_EPHEMERAL = {"type": "ephemeral"}


def _apply_anthropic_caching(
    kw: Dict[str, Any],
    prompt_caching: PromptCacheParam,
) -> None:
    """
    Apply Anthropic prompt caching breakpoints to tools, system, and/or user messages.

    Mutates kw in-place to add cache_control markers at specified locations.
    """
    if "tools" in prompt_caching:
        tools = kw.get("tools")
        if tools and len(tools) > 0:
            tools[-1]["cache_control"] = CACHE_CONTROL_EPHEMERAL

    messages = kw.get("messages")
    if not messages:
        return

    if "system" in prompt_caching:
        # Flatten all system messages into a sequence of (target, is_static)
        # pairs, then find the optimal breakpoint across all of them.
        # "target" is the dict to annotate with cache_control — either a
        # content block (for list content) or the message itself (for string).
        targets: List[Tuple[Dict[str, Any], bool]] = []
        for msg in messages:
            if msg.get("role") != "system":
                continue
            content = msg.get("content")
            if isinstance(content, list) and len(content) > 0:
                for item in content:
                    targets.append((item, item.get("_static", True)))
            else:
                targets.append((msg, msg.get("_static", True)))

        inject_target = None
        for target, is_static in targets:
            if not is_static:
                break
            inject_target = target
        if inject_target is not None:
            inject_target["cache_control"] = CACHE_CONTROL_EPHEMERAL

    if "messages" in prompt_caching:
        for msg in reversed(messages):
            content = msg.get("content")
            if content is not None:
                if isinstance(content, list) and len(content) > 0:
                    content[-1]["cache_control"] = CACHE_CONTROL_EPHEMERAL
                else:
                    msg["cache_control"] = CACHE_CONTROL_EPHEMERAL
                break


def _strip_internal_annotations(kw: Dict[str, Any]) -> None:
    """Strip underscore-prefixed keys from messages and content blocks.

    Keys like ``_static``, ``_time_context``, ``_ctx_header`` etc. are internal
    annotations consumed by unillm's preprocessing.  They must never reach a
    provider API.  Operates on the already-deep-copied messages inside *kw*.
    """
    for msg in kw.get("messages", []):
        for key in [k for k in msg if k.startswith("_")]:
            del msg[key]
        content = msg.get("content")
        if isinstance(content, list):
            for block in content:
                if isinstance(block, dict):
                    for key in [k for k in block if k.startswith("_")]:
                        del block[key]


def _apply_context_1m_beta(kw: Dict[str, Any]) -> None:
    """Inject the 1M context window beta header for supported models."""
    from ..endpoints.anthropic import CONTEXT_1M_BETA, CONTEXT_1M_MODELS

    if kw.get("model") not in CONTEXT_1M_MODELS:
        return
    headers = kw.get("extra_headers") or {}
    existing = headers.get("anthropic-beta", "")
    if CONTEXT_1M_BETA not in existing:
        headers["anthropic-beta"] = (
            f"{existing},{CONTEXT_1M_BETA}" if existing else CONTEXT_1M_BETA
        )
        kw["extra_headers"] = headers


def _uses_anthropic_adaptive_thinking(kw: Dict[str, Any]) -> bool:
    from ..endpoints.anthropic import ADAPTIVE_THINKING_MODELS

    return kw.get("model") in ADAPTIVE_THINKING_MODELS


def _strip_rejected_sampling_params(kw: Dict[str, Any]) -> None:
    """Drop sampling params on models that hard-reject them (Opus 4.7+)."""
    from ..endpoints.anthropic import SAMPLING_PARAMS_REJECTED_MODELS

    if kw.get("model") not in SAMPLING_PARAMS_REJECTED_MODELS:
        return
    for param in ("temperature", "top_p", "top_k"):
        kw.pop(param, None)


def _apply_anthropic_adaptive_thinking(kw: Dict[str, Any]) -> None:
    effort = kw.pop("reasoning_effort", None)
    if effort is None or not _uses_anthropic_adaptive_thinking(kw):
        if effort is not None:
            kw["reasoning_effort"] = effort
        return

    if kw.get("response_format") is not None:
        return

    kw["thinking"] = {"type": "adaptive"}
    output_config = dict(kw.get("output_config") or {})
    output_config["effort"] = effort
    kw["output_config"] = output_config


def _apply_deepseek_thinking_compliance(kw: Dict[str, Any]) -> None:
    for msg in kw.get("messages", []):
        if msg.get("role") == "assistant" and "reasoning_content" not in msg:
            msg["reasoning_content"] = ""


def _forced_tool_name(tool_choice: Any) -> Optional[str]:
    if not isinstance(tool_choice, dict):
        return None
    function_choice = tool_choice.get("function")
    if not isinstance(function_choice, dict):
        return None
    name = function_choice.get("name")
    return name if isinstance(name, str) and name else None


def _is_forced_tool_choice(tool_choice: Any) -> bool:
    return tool_choice == "required" or _forced_tool_name(tool_choice) is not None


def _tool_choice_instruction(tool_choice: Any) -> str:
    name = _forced_tool_name(tool_choice)
    if name is None:
        return TOOL_CHOICE_REQUIRED_INSTRUCTION
    return (
        f"IMPORTANT: You MUST call the `{name}` tool on this turn. "
        "Do not respond with text only and do not choose a different tool."
    )


def _apply_soft_forced_tool_choice_compliance(kw: Dict[str, Any]) -> None:
    tool_choice = kw.get("tool_choice")
    if not _is_forced_tool_choice(tool_choice):
        return

    kw["tool_choice"] = "auto"
    messages = kw.get("messages", [])
    messages.insert(
        0,
        {"role": "system", "content": _tool_choice_instruction(tool_choice)},
    )
    kw["messages"] = messages


def _completed_image_tool_names(messages: List[Dict[str, Any]]) -> set[str]:
    call_id_to_name = {}
    for msg in messages:
        if msg.get("role") != "assistant":
            continue
        for tool_call in msg.get("tool_calls") or []:
            if not isinstance(tool_call, dict):
                continue
            function = tool_call.get("function")
            if not isinstance(function, dict):
                continue
            call_id = tool_call.get("id")
            name = function.get("name")
            if isinstance(call_id, str) and isinstance(name, str) and name:
                call_id_to_name[call_id] = name

    names = set()
    for msg in messages:
        if msg.get("role") != "tool":
            continue
        _, images = _extract_image_blocks(msg.get("content", ""))
        if not images:
            continue
        name = msg.get("name") or call_id_to_name.get(msg.get("tool_call_id"))
        if isinstance(name, str) and name:
            names.add(name)
    return names


def _suppress_tools_after_completed_image_result(
    kw: Dict[str, Any],
    messages: List[Dict[str, Any]],
) -> None:
    completed_image_tools = _completed_image_tool_names(messages)
    if not completed_image_tools:
        return

    kw.pop("tools", None)
    kw.pop("tool_choice", None)


def apply_provider_preprocessing(
    kw: Dict[str, Any],
    provider: Optional[str],
    prompt_caching: Optional[PromptCacheParam] = None,
) -> Dict[str, Any]:
    """Apply provider-specific preprocessing to messages in kw dict (mutates kw)."""
    ensure_response_format_spec(kw)

    messages = kw.get("messages")
    if not messages:
        return kw

    messages = copy.deepcopy(messages)
    kw["messages"] = messages

    if provider == "deepseek":
        spec = get_response_format_spec(kw)
        if spec is not None:
            apply_response_format_transport(spec, provider, kw)
        _apply_deepseek_thinking_compliance(kw)
        _apply_soft_forced_tool_choice_compliance(kw)
        _strip_internal_annotations(kw)
        return kw

    if provider in SOFT_FORCED_TOOL_CHOICE_PROVIDERS:
        if provider == "xiaomi-mimo":
            _suppress_tools_after_completed_image_result(kw, messages)
            messages = _transform_completed_tool_calls_to_context(
                messages,
                context_header=COMPLETED_TOOL_CONTEXT_HEADER,
                context_footer=COMPLETED_TOOL_CONTEXT_FOOTER,
                image_context_footer=COMPLETED_TOOL_IMAGE_CONTEXT_FOOTER,
            )
            kw["messages"] = messages
        _apply_soft_forced_tool_choice_compliance(kw)
        _strip_internal_annotations(kw)
        return kw

    if provider != "anthropic":
        _strip_internal_annotations(kw)
        return kw

    messages = _move_system_messages_to_front(messages)
    messages, combined_any = _combine_adjacent_user_messages(messages)

    if combined_any:
        # Insert explanation after system messages
        insert_pos = sum(1 for m in messages if m.get("role") == "system")
        messages.insert(
            insert_pos,
            {
                "role": "system",
                "content": CONCURRENT_USER_MESSAGES_EXPLANATION,
            },
        )

    # Handle prefilled assistant messages with thinking mode enabled.
    # Anthropic requires thinking_blocks on assistant messages when thinking is enabled.
    # Convert only prefilled messages (before first real response) to system message.
    if kw.get("reasoning_effort") is not None and _has_prefilled_assistant_before_real(
        messages,
    ):
        messages = _convert_prefill_to_system_message(messages)

    # Handle non-compliant mid-conversation tool call messages with thinking enabled.
    # When thinking mode is active, any assistant message with tool_calls must have
    # thinking_blocks. Synthetic messages (from tool loops) or messages from before
    # thinking was enabled won't have these. Transform them to user context messages.
    if kw.get("reasoning_effort") is not None:
        messages = _apply_thinking_compliance(messages)

    # Strip thinking_blocks when reasoning is disabled.
    # If messages contain thinking_blocks from a previous thinking-enabled conversation,
    # but reasoning is not enabled for this request, Anthropic will reject with:
    # "When thinking is disabled, an assistant message cannot contain thinking."
    if kw.get("reasoning_effort") is None:
        messages = _strip_thinking_blocks(messages)

    kw["messages"] = messages

    # Anthropic requires tools=[] (not None) when messages contain tool-related content.
    # This allows tool availability to change turn-by-turn while preserving history.
    if kw.get("tools") is None:
        kw["tools"] = []

    # Handle thinking mode + tool_choice="required" conflict.
    # Anthropic's API forbids thinking when tool_choice forces tool use.
    # Instead of disabling thinking (losing intelligence), we:
    # 1. Keep reasoning_effort enabled
    # 2. Downgrade tool_choice from "required" to "auto"
    # 3. Add a system message instructing the model to call a tool
    # Post-processing (provider_postprocessing.py) handles retry if needed.
    if kw.get("reasoning_effort") is not None and kw.get("tool_choice") == "required":
        kw["tool_choice"] = "auto"
        # Insert tool instruction as first system message
        messages = kw.get("messages", [])
        messages.insert(
            0,
            {"role": "system", "content": TOOL_CHOICE_REQUIRED_INSTRUCTION},
        )
        kw["messages"] = messages

    _apply_context_1m_beta(kw)
    _apply_anthropic_adaptive_thinking(kw)
    _strip_rejected_sampling_params(kw)

    if prompt_caching:
        _apply_anthropic_caching(kw, prompt_caching)

    _strip_internal_annotations(kw)

    return kw
