"""Provider-specific message preprocessing applied before cache lookup."""

import copy
import json
from typing import Any, Callable, Dict, List, Optional, Tuple

from ..types import PromptCacheParam

CONCURRENT_USER_MESSAGES_EXPLANATION = (
    "For all user messages which are represented in JSON format, please treat each "
    "item in the list as a separate message. The user message is shown in JSON format "
    "because this API does not natively support concurrent user messages (which is "
    "what actually occurred), and concurrent user messages are being represented this "
    "way instead."
)

THINKING_PREFILL_EXPLANATION = (
    "The conversation history up to this point is expressed below in JSON format "
    "due to schema constraints:\n"
)

THINKING_COMPLIANCE_CONTEXT_HEADER = "[Prior tool execution context]"
THINKING_COMPLIANCE_CONTEXT_FOOTER = "[Continue from here]"


def _move_system_messages_to_front(
    messages: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Move all system messages to the beginning, preserving relative order."""
    system = [m for m in messages if m.get("role") == "system"]
    non_system = [m for m in messages if m.get("role") != "system"]
    return system + non_system


# ═══════════════════════════════════════════════════════════════════════════════
# Thinking Compliance: Transform non-compliant tool call messages
# ═══════════════════════════════════════════════════════════════════════════════
#
# When Claude extended thinking is enabled (reasoning_effort is set), Anthropic
# requires that all assistant messages have thinking_blocks. However, synthetic
# messages (generated by tool loops for bookkeeping) or messages from before
# thinking was enabled won't have these blocks.
#
# This transformation detects such non-compliant messages and converts them to
# user context messages, preserving the information while making the transcript
# API-compliant.


def _is_non_compliant_assistant_tool_call(msg: Dict[str, Any]) -> bool:
    """
    Check if an assistant message with tool_calls lacks thinking_blocks.

    When thinking mode is enabled, Claude requires thinking_blocks on all
    assistant messages. An assistant message with tool_calls but no
    thinking_blocks is non-compliant and needs transformation.

    Args:
        msg: A message dict to check.

    Returns:
        True if the message is an assistant message with tool_calls but no
        thinking_blocks, False otherwise.
    """
    if not isinstance(msg, dict):
        return False
    if msg.get("role") != "assistant":
        return False
    if not msg.get("tool_calls"):
        return False
    # Has tool_calls but no thinking_blocks → non-compliant
    return not msg.get("thinking_blocks")


def _has_non_compliant_tool_calls(messages: List[Dict[str, Any]]) -> bool:
    """
    Check if any assistant message with tool_calls lacks thinking_blocks.

    Args:
        messages: List of message dicts.

    Returns:
        True if any assistant message with tool_calls is missing thinking_blocks.
    """
    return any(_is_non_compliant_assistant_tool_call(m) for m in messages)


def _transform_tool_calls_to_context(
    messages: List[Dict[str, Any]],
    *,
    context_header: str = THINKING_COMPLIANCE_CONTEXT_HEADER,
    context_footer: str = THINKING_COMPLIANCE_CONTEXT_FOOTER,
    predicate: Optional[Callable[[Dict[str, Any]], bool]] = None,
) -> List[Dict[str, Any]]:
    """
    Transform non-compliant assistant tool call messages into user context.

    When Claude extended thinking is enabled but an assistant message has
    tool_calls without thinking_blocks, this function transforms that message
    (and its paired tool results) into a user message with JSON context.

    The transformation:
    1. Finds assistant messages matching the predicate (or all non-compliant ones)
    2. Collects the assistant message and all following tool result messages
    3. Replaces them with a single user message containing the JSON representation

    Args:
        messages: List of message dicts to transform.
        context_header: Header text for the context block.
        context_footer: Footer text prompting continuation.
        predicate: Optional function to determine which assistant messages to
                   transform. If None, transforms all non-compliant messages.

    Returns:
        New list with non-compliant messages transformed to user context.
    """
    if predicate is None:
        predicate = _is_non_compliant_assistant_tool_call

    result = []
    i = 0

    while i < len(messages):
        msg = messages[i]

        # Check if this is an assistant message we should transform
        if predicate(msg):
            # Collect this assistant message and all following tool messages
            context_messages = [msg]
            j = i + 1

            # Collect all tool result messages that follow
            while j < len(messages) and messages[j].get("role") == "tool":
                context_messages.append(messages[j])
                j += 1

            # Transform to user context message
            context_json = json.dumps(context_messages, indent=2)
            context_content = f"{context_header}\n{context_json}\n{context_footer}"

            result.append({"role": "user", "content": context_content})
            i = j  # Skip past all collected messages
        else:
            result.append(msg)
            i += 1

    return result


def _apply_thinking_compliance(
    messages: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Ensure all assistant messages with tool_calls have thinking_blocks.

    For Claude extended thinking mode, assistant messages must have
    thinking_blocks. This function transforms any non-compliant messages
    (those with tool_calls but no thinking_blocks) into user context messages.

    Args:
        messages: List of message dicts.

    Returns:
        New list with non-compliant messages transformed.
    """
    if not _has_non_compliant_tool_calls(messages):
        return messages

    return _transform_tool_calls_to_context(messages)


def _find_first_real_assistant_index(messages: List[Dict[str, Any]]) -> Optional[int]:
    """
    Find the index of the first assistant message with thinking_blocks (real response).
    Returns None if no real assistant responses exist.
    """
    for i, msg in enumerate(messages):
        if msg.get("role") == "assistant" and msg.get("thinking_blocks"):
            return i
    return None


def _has_prefilled_assistant_before_real(messages: List[Dict[str, Any]]) -> bool:
    """
    Check if there are prefilled assistant messages (without thinking_blocks)
    that appear before any real assistant response (with thinking_blocks).
    """
    first_real_idx = _find_first_real_assistant_index(messages)

    # Check messages up to (but not including) first real response
    check_until = first_real_idx if first_real_idx is not None else len(messages)

    for i in range(check_until):
        msg = messages[i]
        if msg.get("role") == "assistant" and not msg.get("thinking_blocks"):
            return True
    return False


def _convert_prefill_to_system_message(
    messages: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Convert prefilled messages to a system message for Anthropic thinking mode.

    When thinking mode is enabled, Anthropic requires assistant messages to have
    thinking_blocks. For prefilled/synthetic assistant messages, we convert them
    to a JSON representation in the system message.

    Only messages BEFORE the first real assistant response (one with thinking_blocks)
    are converted. Messages from the first real response onwards are kept intact.
    """
    first_real_idx = _find_first_real_assistant_index(messages)

    # Determine which messages to convert vs keep
    if first_real_idx is not None:
        to_convert = messages[:first_real_idx]
        to_keep = messages[first_real_idx:]
    else:
        to_convert = messages
        to_keep = []

    # Extract existing system message content from the portion to convert
    system_content = ""
    non_system_to_convert = []
    for msg in to_convert:
        if msg.get("role") == "system":
            if system_content:
                system_content += "\n\n"
            system_content += msg.get("content", "")
        else:
            non_system_to_convert.append(msg)

    # Build result
    result = []

    # Add system message with converted content (if any non-system messages to convert)
    if non_system_to_convert:
        if system_content:
            system_content += "\n\n"
        system_content += THINKING_PREFILL_EXPLANATION
        system_content += json.dumps(non_system_to_convert, indent=4)

    if system_content:
        result.append({"role": "system", "content": system_content})

    # Add continuation prompt if we converted everything (no real messages to keep)
    if not to_keep:
        result.append({"role": "user", "content": "[continue]"})
    else:
        # Keep real messages intact
        result.extend(to_keep)

    return result


def _combine_adjacent_user_messages(
    messages: List[Dict[str, Any]],
) -> Tuple[List[Dict[str, Any]], bool]:
    """
    Combine adjacent user messages into JSON content array format.
    Returns (result, whether_any_combining_occurred).
    """
    if not messages:
        return [], False

    result = []
    combined_any = False
    i = 0

    while i < len(messages):
        msg = messages[i]

        if msg.get("role") != "user":
            result.append(msg)
            i += 1
            continue

        # Collect adjacent user messages
        user_contents = []
        while i < len(messages) and messages[i].get("role") == "user":
            user_contents.append(messages[i].get("content", ""))
            i += 1

        if len(user_contents) == 1:
            result.append(msg)
        else:
            combined_any = True
            result.append(
                {
                    "role": "user",
                    "content": json.dumps(
                        {
                            "role": "user",
                            "content": [
                                {"type": "text", "text": c} for c in user_contents
                            ],
                        },
                        indent=4,
                    ),
                },
            )

    return result, combined_any


CACHE_CONTROL_EPHEMERAL = {"type": "ephemeral"}


def _apply_anthropic_caching(
    kw: Dict[str, Any],
    prompt_caching: PromptCacheParam,
) -> None:
    """
    Apply Anthropic prompt caching breakpoints to tools, system, and/or user messages.

    Mutates kw in-place to add cache_control markers at specified locations.
    """
    if "tools" in prompt_caching:
        tools = kw.get("tools")
        if tools and len(tools) > 0:
            tools[-1]["cache_control"] = CACHE_CONTROL_EPHEMERAL

    messages = kw.get("messages")
    if not messages:
        return

    if "system" in prompt_caching:
        for msg in reversed(messages):
            if msg.get("role") == "system":
                content = msg.get("content")
                if isinstance(content, list) and len(content) > 0:
                    content[-1]["cache_control"] = CACHE_CONTROL_EPHEMERAL
                else:
                    msg["cache_control"] = CACHE_CONTROL_EPHEMERAL
                break

    if "user" in prompt_caching:
        for msg in reversed(messages):
            if msg.get("role") == "user":
                content = msg.get("content")
                if isinstance(content, list) and len(content) > 0:
                    content[-1]["cache_control"] = CACHE_CONTROL_EPHEMERAL
                else:
                    msg["cache_control"] = CACHE_CONTROL_EPHEMERAL
                break


def apply_provider_preprocessing(
    kw: Dict[str, Any],
    provider: Optional[str],
    prompt_caching: Optional[PromptCacheParam] = None,
) -> Dict[str, Any]:
    """Apply provider-specific preprocessing to messages in kw dict (mutates kw)."""
    messages = kw.get("messages")
    if not messages:
        return kw

    # Only Anthropic preprocessing for now
    if provider != "anthropic":
        return kw

    messages = copy.deepcopy(messages)
    messages = _move_system_messages_to_front(messages)
    messages, combined_any = _combine_adjacent_user_messages(messages)

    if combined_any:
        # Insert explanation after system messages
        insert_pos = sum(1 for m in messages if m.get("role") == "system")
        messages.insert(
            insert_pos,
            {
                "role": "system",
                "content": CONCURRENT_USER_MESSAGES_EXPLANATION,
            },
        )

    # Handle prefilled assistant messages with thinking mode enabled.
    # Anthropic requires thinking_blocks on assistant messages when thinking is enabled.
    # Convert only prefilled messages (before first real response) to system message.
    if kw.get("reasoning_effort") is not None and _has_prefilled_assistant_before_real(
        messages,
    ):
        messages = _convert_prefill_to_system_message(messages)

    # Handle non-compliant mid-conversation tool call messages with thinking enabled.
    # When thinking mode is active, any assistant message with tool_calls must have
    # thinking_blocks. Synthetic messages (from tool loops) or messages from before
    # thinking was enabled won't have these. Transform them to user context messages.
    if kw.get("reasoning_effort") is not None:
        messages = _apply_thinking_compliance(messages)

    kw["messages"] = messages

    # Anthropic requires tools=[] (not None) when messages contain tool-related content.
    # This allows tool availability to change turn-by-turn while preserving history.
    if kw.get("tools") is None:
        kw["tools"] = []

    # Disable thinking mode if tool choice is required
    if kw.get("reasoning_effort") is not None and kw.get("tool_choice") == "required":
        del kw["reasoning_effort"]

    if prompt_caching:
        _apply_anthropic_caching(kw, prompt_caching)

    return kw
